# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comments_pb.comments_pb2 as comments__pb2


class CommentsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostComment = channel.unary_unary(
                '/comments.Comments/PostComment',
                request_serializer=comments__pb2.Comment.SerializeToString,
                response_deserializer=comments__pb2.PostCommentResponse.FromString,
                )
        self.GetComments = channel.unary_unary(
                '/comments.Comments/GetComments',
                request_serializer=comments__pb2.GetCommentRequest.SerializeToString,
                response_deserializer=comments__pb2.GetCommentResponse.FromString,
                )


class CommentsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostComment': grpc.unary_unary_rpc_method_handler(
                    servicer.PostComment,
                    request_deserializer=comments__pb2.Comment.FromString,
                    response_serializer=comments__pb2.PostCommentResponse.SerializeToString,
            ),
            'GetComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComments,
                    request_deserializer=comments__pb2.GetCommentRequest.FromString,
                    response_serializer=comments__pb2.GetCommentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comments.Comments', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Comments(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comments.Comments/PostComment',
            comments__pb2.Comment.SerializeToString,
            comments__pb2.PostCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comments.Comments/GetComments',
            comments__pb2.GetCommentRequest.SerializeToString,
            comments__pb2.GetCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
